services:
  postgres:
    image: postgres:16.3
    container_name: crollo_database
    environment:
      POSTGRES_DB: crollo
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 45100ae0f8b5cdf433ea73ac46996af5b90d07aab540dbe9ade785c3e290f2d3
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - pgdata:/var/lib/postgresql/data

    ports:
      - "5431:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d crollo"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  pgdata:
